version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          # 依存ライブラリのインストール
          pip install flake8
          # Flake8によるチェック
          flake8 test_calculations.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install pytest
          pytest test_calculations.py --junit-xml=test-results/pytest.xml
      - store_test_results:
          path: test-results
workflows:
  version: 2.1
  myworkflow:
    jobs:
      # マスターブランチの場合のみlintを実行する
      - lint:
          filters:
            branches:
              only: master
      # testの実行にlintを必要とする
      - test:
          requires:
            - lint
